name = "VintageOptimalControl"
uuid = "84e37a3b-b645-40f4-9319-00fc2317d550"
authors = ["Michael Freiberger"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
